
# Site settings
title: Shuya Liu
name: Shuya Liu
email: lsyragnarok@gmail.com
baseurl: ""
url: "https://syuuuga.github.io/"
github_username:  syuuuga
disqus_baseurl: "https://syuuuga.github.io/"
disqus_shortname: https-syuuuga-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Shuya Liu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: syuuuga
    url: https://github.com/syuuuga
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://www.linkedin.com/in/paul-e-soto-2705ab218
    desc: Connect with me on LinkedIn
    share: true
